### ISSUE TITLE
Please provide Linux AppImage for download

### ISSUE THREAD

**Issue by probonopd** [bhavyaagg/Invoice-Generator-Electron#38]
This project is already set up to produce AppImages, so it would be nice if you could provide one for download on GitHub Releases.

https://github.com/bhavyaagg/Invoice-Generator-Electron/blob/6f8ef6fc2ffcaa5d5c4dca62acdf99e210f887eb/package.json#L32

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by bhavyaagg** [comment]
@probonopd Thanks for the advice. Will add the App Image soon.

**Comment by bhavyaagg** [comment]
Hi @probonopd I am not able to create an AppImage. I think the problem is that i am trying to build the AppImage on MacOS while my project has a native dependency. Can you help me out here?

**Comment by bhavyaagg** [comment]
Getting this error: 

dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
Referenced from: /Users/USER/Library/Caches/electron-builder/appimage/appimage-9.0.4/darwin/appimagetool
Reason: image not found

**Comment by bhavyaagg** [comment]
@nimit95 has built this on linux. Will be adding the AppImage as a release.

**Comment by bhavyaagg** [comment]
@probonopd I have added the AppImage in the releases. 
You can check it out here and please provide your review.
https://github.com/bhavyaagg/Invoice-Generator-Electron/releases/tag/v1.0.0

**Comment by probonopd** [comment]
Re-running the tests: https://travis-ci.org/AppImage/appimage.github.io/builds/334516330

**Comment by probonopd** [comment]
Works 👍

**Comment by bhavyaagg** [comment]
Great :)
